/* Modelagem básica */
/*CRIAR BANCO DE DADOS*/
CREATE DATABASE exercicio_clientes;

/*ENTRANDO NO BANCO DE DADOS*/
USE exercicio_clientes;

/*CRIANDO TABELA DE CLIENTES
VARCHAR != CHAR
CHAR É UM TIPO DE CAMPO FIXO, 
POR EXEMPLO: CHAR(10) -> SEMPRE TERÁ 10 CARACTERES, AO COLOCAR APENAS 1, 9 SERÃO EM BRANCO, E SE COLOCAR MAIS DE 10 ELE SERÁ TRUNCADO
*/
/*
enum = conjunto de dados enumerados, so existe no MySql, quando queremos limitar um conjunto de dados em uma coluna.
float -> quebrado, com ponto fluantes float(10, 2) = 10 casas e 2 depois da virgula
int -> inteiros, 
*/
CREATE TABLE clientes(
  nome VARCHAR(30),
  sexo CHAR(1),
  email VARCHAR(30),
  cpf INT(11),
  telefone VARCHAR(30),
  endereco VARCHAR(100)
);

/*VERIFICAR TABELAS*/
SHOW TABLES;

/*VERIFICANDO A ESTRUTURA DE UMA TABELA, Ñ É MUITO SEGURO*/
DESC clientes;

/*INSERINDO DADOS NA TABELA*/

/*OMITINDO AS TABELAS - OS VALORES TEM QUE VIR NA ORDEM DA TABELA, DEVENDO DESCREVER*/
INSERT INTO clientes VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 996880166, '02413393212', 'MARIA LACERDA - RIO DE JANEIRO - RJ');
INSERT INTO clientes VALUES('JORGE', 'M', NULL, 996880166, '03213393212', 'BOM RETIRO - MINAS GERAIS - MG');

/*COLOCANDO AS COLUNAS, MAIS SEGURA, PQ EVITA INVERTER OS CAMPOS.*/
INSERT INTO clientes(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '9965704444', 02416383532);

/*INSERT COMPACTO - SO FUNCIONA NO MYSQL*/
INSERT INTO clientes VALUES('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - SP'),('CARLA', 'F', 'CARLA@GMAIL.COM', 7776665, '66587458', 'SAMUEL SILVA- CENTRO - BH - MG');

/*VERIFICANDO OS DADOS DE UM TABELA
- SELECAO, (PROJECAO) E JUNCAO
*/

/*COMANDO SELECT*/
SELECT NOW();

SELECT NOW() as DATA_HORA, 'RENAN LIMA' as ALUNO;

SELECT 'RENAN LIMA';
-----

SELECT NOME, SEXO, EMAIL FROM clientes;

/*as CLIENTE = ALIAS*/
SELECT NOME as CLIENTE, SEXO, EMAIL FROM clientes;

/*apenas para fins acadêmicos*/
SELECT * FROM clientes;
